name: Build ZincClient

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # Build CloudBurst Protocol
      - name: Make CloudBurst Gradle Wrapper executable
        working-directory: CloudBurstProtocol/Protocol-3.0
        run: chmod +x gradlew

      - name: Build CloudBurst Protocol
        working-directory: CloudBurstProtocol/Protocol-3.0
        run: ./gradlew build

      # Build ZincClientCore
      - name: Make ZincClientCore Gradle Wrapper executable
        working-directory: ZincClientCore
        run: chmod +x gradlew

      - name: Build ZincClientCore
        working-directory: ZincClientCore
        run: ./gradlew build